# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SwiftUIDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxKeyboard', '~> 1.0.0'
  pod 'SwiftDate', '~> 6.1.0'
  pod 'SwiftyBeaver', '~> 1.8.4'
  pod 'Kingfisher', '~> 5.15.0'
  pod 'Moya', '~> 15.0.0-alpha.1'
  
end
